### ISSUE TITLE
How to achieve bulkheading with this solution?

### ISSUE THREAD

**Issue by shivamka1** [AVGP/slickmdc#1]
Let's say I have three layers of workflow in an app, namely, "controllers", "services" and "daos". Now I have wish to include bulkheading. In order to achieve so, I may decide to assign different execution context/dispatchers for each of this layers. 

My doubt is if this solution would work. How can we propagate MDC across dispatchers?

**Comment by AVGP** [comment]
This lib doesn't support bulkheading. Keep in mind: This library is defunct, as far as I am concerned.
