### ISSUE TITLE
Config MdcExecutionContext in application.conf

### ISSUE THREAD

**Issue by shivamka1** [AVGP/slickmdc#2]
Is there a way to configure MdcExecutionContext in "application.conf", the way akka allows like below:
```
default-dispatcher {
  executor = "fork-join-executor"
  fork-join-executor {
    parallelism-min = 2
    parallelism-max = 6
    parallelism-factor = 2.0
  }
  throughput = 100
}
```

If not, can we expect such a possibility in future releases?

**Comment by AVGP** [comment]
I have never used akka. Keep in mind: This library is defunct, as far as I am concerned.
